<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Step-1.-Import-the-necessary-libraries-(pandas)" data-toc-modified-id="Step-1.-Import-the-necessary-libraries-(pandas)-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Step 1. Import the necessary libraries (pandas)</a></span></li><li><span><a href="#Step-2.-Import-the-dataset-from-Teams-(US_Crime_Rates_1960_2014.csv)" data-toc-modified-id="Step-2.-Import-the-dataset-from-Teams-(US_Crime_Rates_1960_2014.csv)-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Step 2. Import the dataset from Teams (US_Crime_Rates_1960_2014.csv)</a></span></li><li><span><a href="#Show-the-last-3-rows-of-the-dataFrame" data-toc-modified-id="Show-the-last-3-rows-of-the-dataFrame-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Show the last 3 rows of the dataFrame</a></span></li><li><span><a href="#Step-3.-Set-the-'Year'-column-as-index" data-toc-modified-id="Step-3.-Set-the-'Year'-column-as-index-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Step 3. Set the 'Year' column as index</a></span></li><li><span><a href="#Step-4.-See-the-first-6-entries,-'Population'-and-'Violent'-columns-only" data-toc-modified-id="Step-4.-See-the-first-6-entries,-'Population'-and-'Violent'-columns-only-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Step 4. See the first 6 entries, 'Population' and 'Violent' columns only</a></span></li><li><span><a href="#Step-6.-What-is-the-number-of-observations-in-the-dataset?" data-toc-modified-id="Step-6.-What-is-the-number-of-observations-in-the-dataset?-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Step 6. What is the number of observations in the dataset?</a></span></li><li><span><a href="#Step-7.-What-is-the-number-of-columns-in-the-dataset?" data-toc-modified-id="Step-7.-What-is-the-number-of-columns-in-the-dataset?-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Step 7. What is the number of columns in the dataset?</a></span></li><li><span><a href="#Step-8.-Print-the-name-of-all-the-columns." data-toc-modified-id="Step-8.-Print-the-name-of-all-the-columns.-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Step 8. Print the name of all the columns.</a></span></li><li><span><a href="#Step-9.-What-is-the-data-type-of-each-column?" data-toc-modified-id="Step-9.-What-is-the-data-type-of-each-column?-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Step 9. What is the data type of each column?</a></span></li><li><span><a href="#Step-10.-Summarize-the-DataFrame." data-toc-modified-id="Step-10.-Summarize-the-DataFrame.-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Step 10. Summarize the DataFrame.</a></span></li><li><span><a href="#Step-11.-What-is-the-average-population-was-in-US-in-1960s-(1960-1969)?" data-toc-modified-id="Step-11.-What-is-the-average-population-was-in-US-in-1960s-(1960-1969)?-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Step 11. What is the average population was in US in 1960s (1960-1969)?</a></span></li><li><span><a href="#Step-12.-What-was-the-most-frequent-type-of-crime-in-2014?" data-toc-modified-id="Step-12.-What-was-the-most-frequent-type-of-crime-in-2014?-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Step 12. What was the most frequent type of crime in 2014?</a></span></li><li><span><a href="#Step-13.-What-was-the-number-of-Robbery-crimes-between-2000-and-2014,-including-both?" data-toc-modified-id="Step-13.-What-was-the-number-of-Robbery-crimes-between-2000-and-2014,-including-both?-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>Step 13. What was the number of Robbery crimes between 2000 and 2014, including both?</a></span></li><li><span><a href="#Step-14.-What-%-of-population-was-killed-in-Murder-crimes-in-2000?" data-toc-modified-id="Step-14.-What-%-of-population-was-killed-in-Murder-crimes-in-2000?-14"><span class="toc-item-num">14&nbsp;&nbsp;</span>Step 14. What % of population was killed in Murder crimes in 2000?</a></span></li><li><span><a href="#Step-15.-By-what-percentage-with-respect-to-Population-did-crime-increase-in-2014-compared-to-1960?" data-toc-modified-id="Step-15.-By-what-percentage-with-respect-to-Population-did-crime-increase-in-2014-compared-to-1960?-15"><span class="toc-item-num">15&nbsp;&nbsp;</span>Step 15. By what percentage with respect to Population did crime increase in 2014 compared to 1960?</a></span></li><li><span><a href="#Step-16.-What-types-of-crime-affected-more-than-1%-of-population-in-2010?-(suppose-each-crime-occurs-only-once-for-each-person)" data-toc-modified-id="Step-16.-What-types-of-crime-affected-more-than-1%-of-population-in-2010?-(suppose-each-crime-occurs-only-once-for-each-person)-16"><span class="toc-item-num">16&nbsp;&nbsp;</span>Step 16. What types of crime affected more than 1% of population in 2010? (suppose each crime occurs only once for each person)</a></span></li><li><span><a href="#Step-17.-In-which-year-the-Violent-crime-rate-(as-%-of-Total)-was-the-lowest?" data-toc-modified-id="Step-17.-In-which-year-the-Violent-crime-rate-(as-%-of-Total)-was-the-lowest?-17"><span class="toc-item-num">17&nbsp;&nbsp;</span>Step 17. In which year the Violent crime rate (as % of Total) was the lowest?</a></span></li><li><span><a href="#Step-18.-In-which-year-the-forcible-rape-crime-rate-(as-%-of-Pupolation)-was-the-highest?" data-toc-modified-id="Step-18.-In-which-year-the-forcible-rape-crime-rate-(as-%-of-Pupolation)-was-the-highest?-18"><span class="toc-item-num">18&nbsp;&nbsp;</span>Step 18. In which year the forcible rape crime rate (as % of Pupolation) was the highest?</a></span></li><li><span><a href="#Step-19-20.-Come-up-with-2-questions-of-your-own-that-you-would-like-to-analyze" data-toc-modified-id="Step-19-20.-Come-up-with-2-questions-of-your-own-that-you-would-like-to-analyze-19"><span class="toc-item-num">19&nbsp;&nbsp;</span>Step 19-20. Come up with 2 questions of your own that you would like to analyze</a></span></li></ul></div>

# Ex2 - Getting and Knowing your Data



### Step 1. Import the necessary libraries (pandas)

In [8]:
import pandas as pd

### Step 2. Import the dataset from Teams (US_Crime_Rates_1960_2014.csv)

In [20]:
dataset = pd.read_csv('US_Crime_Rates_1960_2014.csv', index_col='Year', sep = ';')
dataset

,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,,
1960,179323175,3384200,288460,3095700,9110,17190,107840,154320,912100,1855400,328200
1961,182992000,3488000,289390,3198600,8740,17220,106670,156760,949600,1913000,336000
1962,185771000,3752200,301510,3450700,8530,17550,110860,164570,994300,2089600,366800
1963,188483000,4109500,316970,3792500,8640,17650,116470,174210,1086400,2297800,408300
1964,191141000,4564600,364220,4200400,9360,21420,130390,203050,1213200,2514400,472800
1965,193526000,4739400,387390,4352000,9960,23410,138690,215330,1282500,2572600,496900
1966,195576000,5223500,430180,4793300,11040,25820,157990,235330,1410100,2822000,561200
1967,197457000,5903400,499930,5403500,12240,27620,202910,257160,1632100,3111600,659800
1968,199399000,6720200,595010,6125200,13800,31670,262840,286700,1858900,3482700,783600
1969,201385000,7410900,661870,6749000,14760,37170,298850,311090,1981900,3888600,878500
1970,203235298,8098000,738820,7359200,16000,37990,349860,334970,2205000,4225800,928400
1971,206212000,8588200,816500,7771700,17780,42260,387700,368760,2399300,4424200,948200
1972,208230000,8248800,834900,7413900,18670,46850,376290,393090,2375500,4151200,887200
1973,209851000,8718100,875910,7842200,19640,51400,384220,420650,2565500,4347900,928800
1974,211392000,10253400,974720,9278700,20710,55400,442400,456210,3039200,5262500,977100
1975,213124000,11292400,1039710,10252700,20510,56090,470500,492620,3265300,5977700,1009600
1976,214659000,11349700,1004210,10345500,18780,57080,427810,500530,3108700,6270800,966000
1977,216332000,10984500,1029580,9955000,19120,63500,412610,534350,3071500,5905700,977700
1978,218059000,11209000,1085550,10123400,19560,67610,426930,571460,3128300,5991000,1004100
1979,220099000,12249500,1208030,11041500,21460,76390,480700,629480,3327700,6601000,1112800
1980,225349264,13408300,1344520,12063700,23040,82990,565840,672650,3795200,7136900,1131700
1981,229146000,13423800,1361820,12061900,22520,82500,592910,663900,3779700,7194400,1087800
1982,231534000,12974400,1322390,11652000,21010,78770,553130,669480,3447100,7142500,1062400
1983,233981000,12108600,1258090,10850500,19310,78920,506570,653290,3129900,6712800,1007900
1984,236158000,11881800,1273280,10608500,18690,84230,485010,685350,2984400,6591900,1032200
1985,238740000,12431400,1328800,11102600,18980,88670,497870,723250,3073300,6926400,1102900
1986,240132887,13211869,1489169,11722700,20613,91459,542775,834322,3241410,7257153,1224137
1987,242282918,13508700,1483999,12024700,20096,91110,517704,855088,3236184,7499900,1288674
1988,245807000,13923100,1566220,12356900,20680,92490,542970,910090,3218100,7705900,1432900
1989,248239000,14251400,1646040,12605400,21500,94500,578330,951710,3168200,7872400,1564800
1990,248709873,14475600,1820130,12655500,23440,102560,639270,1054860,3073900,7945700,1635900
1991,252177000,14872900,1911770,12961100,24700,106590,687730,1092740,3157200,8142200,1661700
1992,255082000,14438200,1932270,12505900,23760,109060,672480,1126970,2979900,7915200,1610800
1993,257908000,14144800,1926020,12218800,24530,106010,659870,1135610,2834800,7820900,1563100
1994,260341000,13989500,1857670,12131900,23330,102220,618950,1113180,2712800,7879800,1539300
1995,262755000,13862700,1798790,12063900,21610,97470,580510,1099210,2593800,7997700,1472400
1996,265228572,13493863,1688540,11805300,19650,96250,535590,1037050,2506400,7904700,1394200
1997,267637000,13194571,1634770,11558175,18208,96153,498534,1023201,2460526,7743760,1354189
1998,270296000,12475634,1531044,10944590,16914,93103,446625,974402,2329950,7373886,1240754
1999,272690813,11634378,1426044,10208334,15522,89411,409371,911740,2100739,6955520,1152075
2000,281421906,11608072,1425486,10182586,15586,90178,408016,911706,2050992,6971590,1160002
2001,285317559,11876669,1439480,10437480,16037,90863,423557,909023,2116531,7092267,1228391
2002,287973924,11878954,1423677,10455277,16229,95235,420806,891407,2151252,7057370,1246646
2003,290690788,11826538,1383676,10442862,16528,93883,414235,859030,2154834,7026802,1261226
2004,293656842,11679474,1360088,10319386,16148,95089,401470,847381,2144446,6937089,1237851
2005,296507061,11565499,1390745,10174754,16740,94347,417438,862220,2155448,6783447,1235859
2006,299398484,11401511,1418043,9983568,17030,92757,447403,860853,2183746,6607013,1192809
2007,301621157,11251828,1408337,9843481,16929,90427,445125,855856,2176140,6568572,1095769
2008,304374846,11160543,1392628,9767915,16442,90479,443574,842134,2228474,6588046,958629
2009,307006550,10762956,1325896,9337060,15399,89241,408742,812514,2203313,6338095,795652
2010,309330219,10363873,1251248,9112625,14772,85593,369089,781844,2168457,6204601,739565
2011,311587816,10258774,1206031,9052743,14661,84175,354772,752423,2185140,6151095,716508
2012,313873685,10219059,1217067,9001992,14866,85141,355051,762009,2109932,6168874,723186
2013,316497531,9850445,1199684,8650761,14319,82109,345095,726575,1931835,6018632,700294
2014,318857056,9475816,1197987,8277829,14249,84041,325802,741291,1729806,5858496,689527

### Show the last 3 rows of the dataFrame

In [22]:
dataset.tail(3)

,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,,
2012,313873685,10219059,1217067,9001992,14866,85141,355051,762009,2109932,6168874,723186
2013,316497531,9850445,1199684,8650761,14319,82109,345095,726575,1931835,6018632,700294
2014,318857056,9475816,1197987,8277829,14249,84041,325802,741291,1729806,5858496,689527

### Step 3. Set the 'Year' column as index

In [25]:
dataset.set_index('Year', inplace=True)

KeyError: "None of ['Year'] are in the columns"

### Step 4. See the first 6 entries, 'Population' and 'Violent' columns only

In [26]:
subset = dataset.loc[:, ['Population', 'Violent']]
subset.head(6)

      Population  Violent
Year
1960   179323175   288460
1961   182992000   289390
1962   185771000   301510
1963   188483000   316970
1964   191141000   364220
1965   193526000   387390

### Step 6. What is the number of observations in the dataset?

In [27]:
num_observations = dataset.shape[0]
num_observations

55

### Step 7. What is the number of columns in the dataset?

In [28]:
columns_observations = dataset.shape[1]
columns_observations

11

### Step 8. Print the name of all the columns.

In [29]:
dataset.columns

Index(['Population', 'Total', 'Violent', 'Property', 'Murder', 'Forcible_Rape',
       'Robbery', 'Aggravated_assault', 'Burglary', 'Larceny_Theft',
       'Vehicle_Theft'],
      dtype='object')

### Step 9. What is the data type of each column?

In [30]:
data_types = dataset.dtypes
data_types

Population            int64
Total                 int64
Violent               int64
Property              int64
Murder                int64
Forcible_Rape         int64
Robbery               int64
Aggravated_assault    int64
Burglary              int64
Larceny_Theft         int64
Vehicle_Theft         int64
dtype: object

### Step 10. Summarize the DataFrame.

In [31]:
summary = dataset.describe()
summary

,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
count,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,55.000000,55.000000,55.000000,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01
mean,2.461556e+08,1.060315e+07,1.188806e+06,9.412499e+06,17317.236364,72714.800000,416449.890909,6.811818e+05,2.424017e+06,5.959947e+06,1.028614e+06
std,4.166216e+07,3.175931e+06,4.597107e+05,2.738512e+06,4267.442664,28278.006893,150506.403782,2.960255e+05,7.259004e+05,1.846401e+06,3.455693e+05
min,1.793232e+08,3.384200e+06,2.884600e+05,3.095700e+06,8530.000000,17190.000000,106670.000000,1.543200e+05,9.121000e+05,1.855400e+06,3.282000e+05
25%,2.106215e+08,9.096958e+06,9.253150e+05,8.060014e+06,14819.000000,53400.000000,354911.500000,4.384300e+05,2.105336e+06,4.843350e+06,7.896260e+05
50%,2.422829e+08,1.140151e+07,1.322390e+06,1.018259e+07,17030.000000,84230.000000,423557.000000,7.412910e+05,2.329950e+06,6.591900e+06,1.032200e+06
75%,2.833697e+08,1.308449e+07,1.432762e+06,1.160509e+07,20561.500000,92930.000000,512137.000000,9.002150e+05,3.073600e+06,7.168450e+06,1.239302e+06
max,3.188571e+08,1.487290e+07,1.932270e+06,1.296110e+07,24700.000000,109060.000000,687730.000000,1.135610e+06,3.795200e+06,8.142200e+06,1.661700e+06

### Step 11. What is the average population was in US in 1960s (1960-1969)?

In [33]:
average_population_1960s = dataset.loc['1960':'1969', 'Population']
average_population_1960s = average_population_1960s.mean()
average_population_1960s

191505317.5

### Step 12. What was the most frequent type of crime in 2014?

In [47]:
crime_2014 = dataset.loc['2014']
most_frequent_crime = crime_2014.idxmax()
most_frequent_crime

KeyError: '2014'

### Step 13. What was the number of Robbery crimes between 2000 and 2014, including both?

In [48]:
robbery_crimes = dataset.loc['2000':'2014', 'Robbery']
total_robbery_crimes = robbery_crimes.sum()
total_robbery_crimes

5980175

### Step 14. What % of population was killed in Murder crimes in 2000?

In [55]:
population_2000 = dataset.loc['2000', 'Population']
murder_2000 = dataset.loc['2000', 'Murder']
percentage_population_killed = (murder_2000 / population_2000) * 100
percentage_population_killed

KeyError: '2000'

### Step 15. By what percentage with respect to Population did crime increase in 2014 compared to 1960?

In [56]:
population_1960 = dataset.loc['1960', 'Population']
population_2014 = dataset.loc['2014', 'Population']

total_crime_1960 = dataset.loc['1960', 'Total']
total_crime_2014 = dataset.loc['2014', 'Total']

percentage_increase = ((total_crime_2014 - total_crime_1960) / total_crime_1960) * 100

print(f"The percentage increase in crime with respect to population from 1960 to 2014 was: {percentage_increase:.2f}%")

KeyError: '1960'

### Step 16. What types of crime affected more than 1% of population in 2010? (suppose each crime occurs only once for each person)

In [60]:
population_2010 = dataset.loc['2010', 'Population']

one_percent_population = 0.01 * population_2010

crime_types_more_than_1_percent = dataset.loc['2010', ['Murder', 'Forcible_Rape', 'Robbery', 'Aggravated_assault', 'Burglary', 'Larceny_Theft', 'Vehicle_Theft']]
crime_types_more_than_1_percent = crime_types_more_than_1_percent[crime_types_more_than_1_percent > one_percent_population]
crime_types_more_than_1_percent

KeyError: '2010'

### Step 17. In which year the Violent crime rate (as % of Total) was the lowest?

In [61]:
dataset['Violent_Crime_Rate'] = (dataset['Violent'] / dataset['Total']) * 100

year_with_lowest_rate = dataset['Violent_Crime_Rate'].idxmin()
year_with_lowest_rate

1963

### Step 18. In which year the forcible rape crime rate (as % of Pupolation) was the highest?

In [62]:
dataset['Forcible_Rape_Rate'] = (dataset['Forcible_Rape'] / dataset['Population']) * 100

year_with_highest_rate = dataset['Forcible_Rape_Rate'].idxmax()
year_with_highest_rate

1992

### Step 19-20. Come up with 2 questions of your own that you would like to analyze

# 19. What is the year with the highest number of Burglary crimes?

In [65]:
year_highest_burglary = dataset['Burglary'].idxmax()
highest_burglary_count = dataset['Burglary'].max()
year_highest_burglary

1980

# 20. What is the average population in the dataset?

In [67]:
average_population = dataset['Population'].mean()
average_population

246155585.8909091